services:
  db:
    image: postgres:17-alpine
    container_name: postgres-container
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Muk1nha2005!
      POSTGRES_DB: sos_cidadao
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app-network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sos-api
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/sos_cidadao
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: Muk1nha2005!
    depends_on:
      - db
    command: >
      sh -c "until pg_isready -h db -p 5432 -U postgres; do sleep 1; done; java -jar app.jar"
    networks:
      - app-network

volumes:
  pgdata:

networks:
  app-network:
    driver: bridge
